// 'use client';

import type {Metadata} from 'next';
import {Poppins} from 'next/font/google';
// import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.scss';
import UserStatus from '@/components/auth/UserStatus/UserStatus';
import SignOut from '@/components/auth/SignOut/SignOut';
import ReduxProvider from '@/providers/ReduxProvider';
import Link from 'next/link';
import Header from '@/components/Header/Header';
import MainHeader from '@/components/MainHeader/MainHeader';
import Notifications from '@/components/Notifications/Notifications';
const popins = Poppins({
  subsets: ['latin'], // Здесь можно указать поддерживаемые подмножества
  weight: ['300', '400', '500'],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang='en'>
        <body className={popins.className}>
          <div className='flex-basic'>
            <MainHeader />
            <div className=' wrap-85'>
              <UserStatus />
              {children}
            </div>
            <Notifications />
          </div>
        </body>
      </html>
    </ReduxProvider>
  );
}
