import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import UserStatus from '@/components/auth/UserStatus/UserStatus';
import SignOut from '@/components/auth/SignOut/SignOut';
import ReduxProvider from '@/providers/ReduxProvider';
import Link from 'next/link';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang='en'>
        <body className={inter.className}>
          <UserStatus />
          <Link href={'/user'}>user</Link> <br />
          <br />
          <Link href={'/registration'}>registration</Link>
          <br />
          <br />
          <Link href={'/log-in'}>Log in</Link>
          <br />
          <br />
          <SignOut></SignOut>
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
